// Proposed mobile API routes. These paths are placeholders until backend contracts are implemented.

export const endpoints = {
  auth: {
    currentSession: '/api/mobile/auth/session',
    login: '/api/mobile/auth/login',
    logout: '/api/mobile/auth/logout',
    refreshSession: '/api/mobile/auth/refresh',
  },
  catalog: {
    cities: '/api/mobile/catalog/cities',
    coreCategories: '/api/mobile/catalog/core-categories',
    postingRules: '/api/mobile/catalog/posting-rules',
    proCategories: '/api/mobile/catalog/pro-categories',
  },
  customer: {
    home: '/api/mobile/customer/home',
    homeSummary: '/api/mobile/customer/home',
    messages: '/api/mobile/customer/messages',
    proRequestDetail: (proRequestId: string) => `/api/mobile/customer/pro-requests/${proRequestId}`,
    proRequestImageUpload: (proRequestId: string) => `/api/mobile/customer/pro-requests/${proRequestId}/images`,
    proRequests: '/api/mobile/customer/pro-requests',
    taskApproveCompletion: (taskId: string) => `/api/mobile/customer/tasks/${taskId}/approve-completion`,
    taskCancel: (taskId: string) => `/api/mobile/customer/tasks/${taskId}/cancel`,
    taskDetail: (taskId: string) => `/api/mobile/customer/tasks/${taskId}`,
    taskImageUpload: (taskId: string) => `/api/mobile/customer/tasks/${taskId}/images`,
    taskPaymentFinalize: (taskId: string) => `/api/mobile/customer/tasks/${taskId}/payment/finalize`,
    taskPaymentSetup: (taskId: string) => `/api/mobile/customer/tasks/${taskId}/payment/setup`,
    taskRejectCompletion: (taskId: string) => `/api/mobile/customer/tasks/${taskId}/reject-completion`,
    taskSelectTasker: (taskId: string) => `/api/mobile/customer/tasks/${taskId}/select-tasker`,
    taskSupportRequest: (taskId: string) => `/api/mobile/customer/tasks/${taskId}/support-request`,
    tasks: '/api/mobile/customer/tasks',
  },
  messages: {
    sendMessage: (threadId: string) => `/api/mobile/messages/threads/${encodeURIComponent(threadId)}/messages`,
    threadDetail: (threadId: string) => `/api/mobile/messages/threads/${encodeURIComponent(threadId)}`,
    threads: '/api/mobile/messages/threads',
  },
  notifications: {
    preferences: '/api/mobile/notifications/preferences',
    registerPushToken: '/api/mobile/notifications/register-push-token',
  },
  payments: {
    corePaymentStatus: (taskId: string) => `/api/mobile/payments/core-tasks/${taskId}/status`,
    proAccessStatus: (proRequestId: string) => `/api/mobile/payments/pro-requests/${proRequestId}/access-status`,
  },
  provider: {
    coreTaskDetail: (taskId: string) => `/api/mobile/provider/core-tasks/${taskId}`,
    coreTaskCannotAttend: (taskId: string) => `/api/mobile/provider/core-tasks/${taskId}/cannot-attend`,
    coreTaskInterest: (taskId: string) => `/api/mobile/provider/core-tasks/${taskId}/interest`,
    coreTaskOnTheWay: (taskId: string) => `/api/mobile/provider/core-tasks/${taskId}/on-the-way`,
    coreTaskReportIssue: (taskId: string) => `/api/mobile/provider/core-tasks/${taskId}/report-issue`,
    coreTaskRequestCompletion: (taskId: string) => `/api/mobile/provider/core-tasks/${taskId}/request-completion`,
    coreTaskStart: (taskId: string) => `/api/mobile/provider/core-tasks/${taskId}/start`,
    coreTaskSupportRequest: (taskId: string) => `/api/mobile/provider/core-tasks/${taskId}/support-request`,
    coreTasks: '/api/mobile/provider/core-tasks',
    dashboard: '/api/mobile/provider/dashboard',
    dashboardSummary: '/api/mobile/provider/dashboard',
    messages: '/api/mobile/provider/messages',
    proRequestDetail: (proRequestId: string) => `/api/mobile/provider/pro-requests/${proRequestId}`,
    proRequests: '/api/mobile/provider/pro-requests',
    profile: '/api/mobile/provider/profile',
  },
} as const;
