// Centralized mobile API routes. Screens should use wrappers instead of hardcoding these paths.

export const endpoints = {
  account: {
    changeEmail: '/api/mobile/account/change-email',
    changePassword: '/api/mobile/account/change-password',
  },
  auth: {
    currentSession: '/api/mobile/auth/session',
    forgotPassword: '/api/mobile/auth/forgot-password',
    login: '/api/mobile/auth/login',
    logout: '/api/mobile/auth/logout',
    register: '/api/mobile/auth/register',
    refreshSession: '/api/mobile/auth/refresh',
  },
  catalog: {
    cities: '/api/mobile/catalog/cities',
    coreCategories: '/api/mobile/catalog/core-categories',
    postingRules: '/api/mobile/catalog/posting-rules',
    proCategories: '/api/mobile/catalog/pro-categories',
  },
  customer: {
    home: '/api/mobile/customer/home',
    homeSummary: '/api/mobile/customer/home',
    messages: '/api/mobile/customer/messages',
    paymentsUnlocks: '/api/mobile/customer/payments-unlocks',
    profile: '/api/mobile/customer/profile',
    proRequestAccessCheckout: (proRequestId: string) => `/api/mobile/customer/pro-requests/${proRequestId}/access/checkout`,
    proRequestAccessCredit: (proRequestId: string) => `/api/mobile/customer/pro-requests/${proRequestId}/access/credit`,
    proRequestAccessSupportRequest: (proRequestId: string) => `/api/mobile/customer/pro-requests/${proRequestId}/access/support-request`,
    proRequestDetail: (proRequestId: string) => `/api/mobile/customer/pro-requests/${proRequestId}`,
    proRequestProProfile: (proRequestId: string, proProfileId: string) => `/api/mobile/customer/pro-requests/${proRequestId}/pros/${proProfileId}`,
    proRequestImageUpload: (proRequestId: string) => `/api/mobile/customer/pro-requests/${proRequestId}/images`,
    proRequestDiscardResponse: (proRequestId: string, proResponseId: string) => `/api/mobile/customer/pro-requests/${proRequestId}/responses/${proResponseId}/discard`,
    proRequestSelectResponse: (proRequestId: string, proResponseId: string) => `/api/mobile/customer/pro-requests/${proRequestId}/responses/${proResponseId}/select`,
    proRequestSiteVisitCancel: (proRequestId: string, siteVisitId: string) => `/api/mobile/customer/pro-requests/${proRequestId}/site-visits/${siteVisitId}/cancel`,
    proRequestSiteVisits: (proRequestId: string) => `/api/mobile/customer/pro-requests/${proRequestId}/site-visits`,
    proRequests: '/api/mobile/customer/pro-requests',
    rewards: '/api/mobile/customer/rewards',
    taskApproveCompletion: (taskId: string) => `/api/mobile/customer/tasks/${taskId}/approve-completion`,
    taskBookAgain: (taskId: string) => `/api/mobile/customer/tasks/${taskId}/book-again`,
    taskCancel: (taskId: string) => `/api/mobile/customer/tasks/${taskId}/cancel`,
    taskDetail: (taskId: string) => `/api/mobile/customer/tasks/${taskId}`,
    taskImageUpload: (taskId: string) => `/api/mobile/customer/tasks/${taskId}/images`,
    taskPaymentFinalize: (taskId: string) => `/api/mobile/customer/tasks/${taskId}/payment/finalize`,
    taskPaymentSetup: (taskId: string) => `/api/mobile/customer/tasks/${taskId}/payment/setup`,
    taskRejectCompletion: (taskId: string) => `/api/mobile/customer/tasks/${taskId}/reject-completion`,
    taskSelectTasker: (taskId: string) => `/api/mobile/customer/tasks/${taskId}/select-tasker`,
    taskSupportRequest: (taskId: string) => `/api/mobile/customer/tasks/${taskId}/support-request`,
    tasks: '/api/mobile/customer/tasks',
    support: '/api/mobile/customer/support',
    supportResolution: (supportRequestId: string) => `/api/mobile/customer/support/${supportRequestId}/resolution`,
  },
  messages: {
    sendMessage: (threadId: string) => `/api/mobile/messages/threads/${encodeURIComponent(threadId)}/messages`,
    threadDetail: (threadId: string) => `/api/mobile/messages/threads/${encodeURIComponent(threadId)}`,
    threads: '/api/mobile/messages/threads',
  },
  notifications: {
    list: '/api/mobile/notifications',
    markAllRead: '/api/mobile/notifications/read-all',
    markRead: (notificationId: string) => `/api/mobile/notifications/${notificationId}/read`,
    preferences: '/api/mobile/notifications/preferences',
    registerPushToken: '/api/mobile/notifications/register-token',
    unregisterPushToken: '/api/mobile/notifications/unregister-token',
  },
  payments: {
    corePaymentStatus: (taskId: string) => `/api/mobile/payments/core-tasks/${taskId}/status`,
    proAccessStatus: (proRequestId: string) => `/api/mobile/payments/pro-requests/${proRequestId}/access-status`,
  },
  provider: {
    coreTaskDetail: (taskId: string) => `/api/mobile/provider/core-tasks/${taskId}`,
    coreTaskCannotAttend: (taskId: string) => `/api/mobile/provider/core-tasks/${taskId}/cannot-attend`,
    coreTaskInterest: (taskId: string) => `/api/mobile/provider/core-tasks/${taskId}/interest`,
    coreTaskOnTheWay: (taskId: string) => `/api/mobile/provider/core-tasks/${taskId}/on-the-way`,
    coreTaskReportIssue: (taskId: string) => `/api/mobile/provider/core-tasks/${taskId}/report-issue`,
    coreTaskRequestCompletion: (taskId: string) => `/api/mobile/provider/core-tasks/${taskId}/request-completion`,
    coreTaskStart: (taskId: string) => `/api/mobile/provider/core-tasks/${taskId}/start`,
    coreTaskSupportRequest: (taskId: string) => `/api/mobile/provider/core-tasks/${taskId}/support-request`,
    coreTasks: '/api/mobile/provider/core-tasks',
    dashboard: '/api/mobile/provider/dashboard',
    dashboardSummary: '/api/mobile/provider/dashboard',
    messages: '/api/mobile/provider/messages',
    proRequestDetail: (proRequestId: string) => `/api/mobile/provider/pro-requests/${proRequestId}`,
    proRequestResponse: (proRequestId: string) => `/api/mobile/provider/pro-requests/${proRequestId}/response`,
    proRequestSiteVisitAccept: (proRequestId: string, siteVisitId: string) => `/api/mobile/provider/pro-requests/${proRequestId}/site-visits/${siteVisitId}/accept`,
    proRequestSiteVisitDecline: (proRequestId: string, siteVisitId: string) => `/api/mobile/provider/pro-requests/${proRequestId}/site-visits/${siteVisitId}/decline`,
    proRequestSiteVisitProposeTime: (proRequestId: string, siteVisitId: string) => `/api/mobile/provider/pro-requests/${proRequestId}/site-visits/${siteVisitId}/propose-time`,
    proRequests: '/api/mobile/provider/pro-requests',
    proProfile: '/api/mobile/provider/pro-profile',
    proProfilePortfolio: '/api/mobile/provider/pro-profile/portfolio',
    proProfilePortfolioProject: (projectId: string) => `/api/mobile/provider/pro-profile/portfolio/${encodeURIComponent(projectId)}`,
    proProfilePortfolioProjectPhoto: (projectId: string) => `/api/mobile/provider/pro-profile/portfolio/${encodeURIComponent(projectId)}/photos`,
    proProfilePortfolioProjectPhotoRemove: (projectId: string, imageId: string) => `/api/mobile/provider/pro-profile/portfolio/${encodeURIComponent(projectId)}/photos/${encodeURIComponent(imageId)}`,
    profile: '/api/mobile/provider/profile',
    rewards: '/api/mobile/provider/rewards',
    stripeOnboardingLink: '/api/mobile/provider/stripe/onboarding-link',
    stripeRefreshStatus: '/api/mobile/provider/stripe/refresh-status',
    taskerProfile: '/api/mobile/provider/tasker-profile',
    taskerProfilePhoto: '/api/mobile/provider/tasker-profile/photo',
  },
} as const;
