export { getCurrentSession, loginWithEmailPassword, logoutMobileSession, refreshMobileSession } from './auth';
export { getCities, getCoreCategories, getPostingRules, getProCategories } from './catalog';
export { createApiClient, apiRequest } from './client';
export { assertApiBaseUrl, getApiBaseUrl } from './config';
export {
  createCustomerProRequest,
  createCustomerTask,
  getCustomerHomeSummary,
  getCustomerProRequestDetail,
  getCustomerProRequests,
  getCustomerTaskDetail,
  getCustomerTasks,
} from './customer';
export { endpoints } from './endpoints';
export { uploadCustomerProRequestImage, uploadCustomerTaskImage } from './imageUploads';
export { resolveApiMediaUrl } from './media';
export { getMessageThread, getMessageThreads, sendMessage, sendMessageImage } from './messages';
export {
  expressInterestInCoreTask,
  getProviderCoreTaskDetail,
  getProviderCoreTasks,
  getProviderDashboard,
  getProviderProfile,
  getProviderProRequestDetail,
  getProviderProRequests,
} from './provider';
export {
  getMockCitiesCatalogResponse,
  getMockCoreCategoriesResponse,
  getMockCustomerHomeResponse,
  getMockCustomerHomeSummary,
  getMockCustomerProRequestDetailResponse,
  getMockCustomerProRequestsResponse,
  getMockCustomerTaskDetailResponse,
  getMockCustomerTasksResponse,
  getMockMessageThreadResponse,
  getMockMessageThreadsResponse,
  getMockPostingRulesResponse,
  getMockProviderCoreTaskDetailResponse,
  getMockProviderCoreTasksResponse,
  getMockProviderDashboardResponse,
  getMockProviderDashboardSummary,
  getMockProviderProfileResponse,
  getMockProviderProRequestDetailResponse,
  getMockProviderProRequestsResponse,
  getMockProCategoriesResponse,
  getMockUserSession,
} from './mockApi';
export type { ApiClientConfig, TasklyApiClient } from './client';
export type {
  CustomerHighlight,
  CustomerHomeSummary,
  CustomerImageUploadResponse,
  CustomerHomeResponse,
  CustomerNextAction,
  CreateCustomerProRequestPayload,
  CreateCustomerProRequestResponse,
  CreateCustomerTaskPayload,
  CreateCustomerTaskResponse,
  CatalogCategory,
  CatalogCategoriesResponse,
  CitiesCatalogResponse,
  CityOption,
  CoreTaskPostingRules,
  CustomerProRequestDetail,
  CustomerProRequestDetailResponse,
  CustomerProRequestSummary,
  CustomerProRequestsResponse,
  CustomerProResponsePreview,
  CustomerTaskDetail,
  CustomerTaskDetailResponse,
  CustomerTaskSummary,
  CustomerTasksResponse,
  DetailImage,
  DetailNextAction,
  DetailTimelineItem,
  EmptyStateContent,
  EligibilitySummary,
  ExpressInterestInCoreTaskPayload,
  ExpressInterestInCoreTaskResponse,
  MessageThreadSummary,
  MessageAccent,
  MessageContextType,
  MessageItem,
  MessageAttachment,
  MessageSenderRole,
  MessageReadOnlyReason,
  MessageThreadCapabilities,
  MessageThreadDetailResponse,
  MessageThreadMeta,
  MessageThreadsResponse,
  NextAction,
  NotificationPreferenceSummary,
  PaymentActionState,
  ProRequestDetail,
  ProRequestSummary,
  ProResponsePreview,
  ProviderCoreTaskDetail,
  ProviderCoreTaskDetailResponse,
  ProviderCoreTaskNextActions,
  ProviderCoreTasksResponse,
  ProviderCoreTaskSummary,
  ProviderDashboardCard,
  ProviderDashboardResponse,
  ProviderDashboardSummary,
  ProviderNextAction,
  ProviderProfileResponse,
  ProviderProfileSummary,
  ProviderProCategoryStatus,
  ProviderProRequestDetail,
  ProviderProRequestDetailResponse,
  ProviderProRequestsResponse,
  ProviderProRequestSummary,
  ProviderProResponseSummary,
  SendMessageResponse,
  PostingRulesResponse,
  ProRequestPostingRules,
  TaskDetail,
  TaskSummary,
} from './domain';
export type {
  ApiError,
  ApiRequestOptions,
  ApiResult,
  AuthTokens,
  LoginRequest,
  LoginResponse,
  LogoutResponse,
  PermissionSummary,
  ProviderCapabilities,
  RefreshRequest,
  RefreshResponse,
  SessionNextAction,
  SessionNextActionType,
  UserSession,
  WorkspaceAccess,
} from './types';

export const apiFoundationStatus = 'not-connected';
