export { getCurrentSession, loginWithEmailPassword, logoutMobileSession, refreshMobileSession } from './auth';
export { getCities, getCoreCategories, getPostingRules, getProCategories } from './catalog';
export { createApiClient, apiRequest } from './client';
export { assertApiBaseUrl, getApiBaseUrl } from './config';
export {
  createCustomerTask,
  getCustomerHomeSummary,
  getCustomerProRequestDetail,
  getCustomerProRequests,
  getCustomerTaskDetail,
  getCustomerTasks,
} from './customer';
export { endpoints } from './endpoints';
export {
  getProviderCoreTaskDetail,
  getProviderCoreTasks,
  getProviderDashboard,
  getProviderProfile,
  getProviderProRequestDetail,
  getProviderProRequests,
} from './provider';
export {
  getMockCitiesCatalogResponse,
  getMockCoreCategoriesResponse,
  getMockCustomerHomeResponse,
  getMockCustomerHomeSummary,
  getMockCustomerProRequestDetailResponse,
  getMockCustomerProRequestsResponse,
  getMockCustomerTaskDetailResponse,
  getMockCustomerTasksResponse,
  getMockPostingRulesResponse,
  getMockProviderCoreTaskDetailResponse,
  getMockProviderCoreTasksResponse,
  getMockProviderDashboardResponse,
  getMockProviderDashboardSummary,
  getMockProviderProfileResponse,
  getMockProviderProRequestDetailResponse,
  getMockProviderProRequestsResponse,
  getMockProCategoriesResponse,
  getMockUserSession,
} from './mockApi';
export type { ApiClientConfig, TasklyApiClient } from './client';
export type {
  CustomerHighlight,
  CustomerHomeSummary,
  CustomerHomeResponse,
  CustomerNextAction,
  CreateCustomerTaskPayload,
  CreateCustomerTaskResponse,
  CatalogCategory,
  CatalogCategoriesResponse,
  CitiesCatalogResponse,
  CityOption,
  CoreTaskPostingRules,
  CustomerProRequestDetail,
  CustomerProRequestDetailResponse,
  CustomerProRequestSummary,
  CustomerProRequestsResponse,
  CustomerProResponsePreview,
  CustomerTaskDetail,
  CustomerTaskDetailResponse,
  CustomerTaskSummary,
  CustomerTasksResponse,
  DetailImage,
  DetailNextAction,
  DetailTimelineItem,
  EmptyStateContent,
  EligibilitySummary,
  MessageThreadSummary,
  NextAction,
  NotificationPreferenceSummary,
  PaymentActionState,
  ProRequestDetail,
  ProRequestSummary,
  ProResponsePreview,
  ProviderCoreTaskDetail,
  ProviderCoreTaskDetailResponse,
  ProviderCoreTasksResponse,
  ProviderCoreTaskSummary,
  ProviderDashboardCard,
  ProviderDashboardResponse,
  ProviderDashboardSummary,
  ProviderNextAction,
  ProviderProfileResponse,
  ProviderProfileSummary,
  ProviderProCategoryStatus,
  ProviderProRequestDetail,
  ProviderProRequestDetailResponse,
  ProviderProRequestsResponse,
  ProviderProRequestSummary,
  ProviderProResponseSummary,
  PostingRulesResponse,
  ProRequestPostingRules,
  TaskDetail,
  TaskSummary,
} from './domain';
export type {
  ApiError,
  ApiRequestOptions,
  ApiResult,
  AuthTokens,
  LoginRequest,
  LoginResponse,
  LogoutResponse,
  PermissionSummary,
  ProviderCapabilities,
  RefreshRequest,
  RefreshResponse,
  SessionNextAction,
  SessionNextActionType,
  UserSession,
  WorkspaceAccess,
} from './types';

export const apiFoundationStatus = 'not-connected';
